# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Chapter10\BackProjectionBH.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 680)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/python_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.dynamic_range = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dynamic_range.sizePolicy().hasHeightForWidth())
        self.dynamic_range.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dynamic_range.setFont(font)
        self.dynamic_range.setObjectName("dynamic_range")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.dynamic_range)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.polarization = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polarization.sizePolicy().hasHeightForWidth())
        self.polarization.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.polarization.setFont(font)
        self.polarization.setObjectName("polarization")
        self.polarization.addItem("")
        self.polarization.addItem("")
        self.polarization.addItem("")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.polarization)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.el_start_end = QtWidgets.QLineEdit(self.centralwidget)
        self.el_start_end.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.el_start_end.setFont(font)
        self.el_start_end.setObjectName("el_start_end")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.el_start_end)
        self.az_start_end = QtWidgets.QLineEdit(self.centralwidget)
        self.az_start_end.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.az_start_end.setFont(font)
        self.az_start_end.setObjectName("az_start_end")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.az_start_end)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.frequency = QtWidgets.QLineEdit(self.centralwidget)
        self.frequency.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.frequency.setFont(font)
        self.frequency.setObjectName("frequency")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.frequency)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.x_span = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.x_span.setFont(font)
        self.x_span.setObjectName("x_span")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.x_span)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.y_span = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.y_span.setFont(font)
        self.y_span.setObjectName("y_span")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.y_span)
        self.z_span = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.z_span.setFont(font)
        self.z_span.setObjectName("z_span")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.z_span)
        self.nx_ny_nz = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nx_ny_nz.setFont(font)
        self.nx_ny_nz.setObjectName("nx_ny_nz")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.nx_ny_nz)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.window_type = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.window_type.setFont(font)
        self.window_type.setObjectName("window_type")
        self.window_type.addItem("")
        self.window_type.addItem("")
        self.window_type.addItem("")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.window_type)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 20)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Back Projection"))
        self.label_6.setText(_translate("MainWindow", "Input"))
        self.label_12.setText(_translate("MainWindow", "Dynamic Range (dB)"))
        self.dynamic_range.setText(_translate("MainWindow", "50"))
        self.label_4.setText(_translate("MainWindow", "Polarization"))
        self.polarization.setItemText(0, _translate("MainWindow", "VV"))
        self.polarization.setItemText(1, _translate("MainWindow", "HH"))
        self.polarization.setItemText(2, _translate("MainWindow", "HV"))
        self.label_2.setText(_translate("MainWindow", "Elevation (deg)"))
        self.el_start_end.setText(_translate("MainWindow", "18, 23"))
        self.az_start_end.setText(_translate("MainWindow", "66, 71"))
        self.label.setText(_translate("MainWindow", "Azimuth (deg)"))
        self.frequency.setText(_translate("MainWindow", "7, 13"))
        self.label_3.setText(_translate("MainWindow", "Frequency (GHz)"))
        self.x_span.setText(_translate("MainWindow", "10"))
        self.label_5.setText(_translate("MainWindow", "Image Span-X (m)"))
        self.y_span.setText(_translate("MainWindow", "10"))
        self.z_span.setText(_translate("MainWindow", "10"))
        self.nx_ny_nz.setText(_translate("MainWindow", "10, 10, 10"))
        self.label_7.setText(_translate("MainWindow", "Image Span-Y (m)"))
        self.label_8.setText(_translate("MainWindow", "Image Span-Z (m)"))
        self.label_9.setText(_translate("MainWindow", "Number of pixels (nx, ny, nz)"))
        self.window_type.setItemText(0, _translate("MainWindow", "Rectangular"))
        self.window_type.setItemText(1, _translate("MainWindow", "Hanning"))
        self.window_type.setItemText(2, _translate("MainWindow", "Hamming"))
        self.label_10.setText(_translate("MainWindow", "Window Type"))

import Libs.resources_rc
