# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Chapter01\RadarBook.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(575, 505)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/python_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowser.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser.setFont(font)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Panel)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.toolsTree = QtWidgets.QTreeWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.toolsTree.setFont(font)
        self.toolsTree.setFrameShape(QtWidgets.QFrame.Panel)
        self.toolsTree.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.toolsTree.setObjectName("toolsTree")
        font = QtGui.QFont()
        font.setPointSize(16)
        self.toolsTree.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolsTree)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolsTree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolsTree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolsTree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolsTree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolsTree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolsTree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolsTree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolsTree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolsTree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolsTree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout.addWidget(self.toolsTree)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Introduction to Radar"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:24pt; font-weight:600;\">Introduction to Radar using Python and MATLAB</span></p></body></html>"))
        self.toolsTree.headerItem().setText(0, _translate("MainWindow", "Python Examples"))
        __sortingEnabled = self.toolsTree.isSortingEnabled()
        self.toolsTree.setSortingEnabled(False)
        self.toolsTree.topLevelItem(0).setText(0, _translate("MainWindow", "Chapter 1 - Introduction"))
        self.toolsTree.topLevelItem(1).setText(0, _translate("MainWindow", "Chapter 2 - EM Fields and Waves"))
        self.toolsTree.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Plane Waves"))
        self.toolsTree.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Reflection / Transmission"))
        self.toolsTree.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "Apparent Elevation"))
        self.toolsTree.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "Apparent Range"))
        self.toolsTree.topLevelItem(1).child(4).setText(0, _translate("MainWindow", "Beam Spreading"))
        self.toolsTree.topLevelItem(1).child(5).setText(0, _translate("MainWindow", "Ducting"))
        self.toolsTree.topLevelItem(1).child(6).setText(0, _translate("MainWindow", "Diffraction"))
        self.toolsTree.topLevelItem(1).child(7).setText(0, _translate("MainWindow", "Atmospheric Attenuation"))
        self.toolsTree.topLevelItem(1).child(8).setText(0, _translate("MainWindow", "Vegetation Attenuation"))
        self.toolsTree.topLevelItem(1).child(9).setText(0, _translate("MainWindow", "Rain Attenuation"))
        self.toolsTree.topLevelItem(1).child(10).setText(0, _translate("MainWindow", "Cloud/Fog Attenuation"))
        self.toolsTree.topLevelItem(2).setText(0, _translate("MainWindow", "Chapter 3 - Antennas"))
        self.toolsTree.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Linear Wires"))
        self.toolsTree.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Loop Antenna"))
        self.toolsTree.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "Rectangular Aperture"))
        self.toolsTree.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "Circular Aperture"))
        self.toolsTree.topLevelItem(2).child(4).setText(0, _translate("MainWindow", "Horn Antenna"))
        self.toolsTree.topLevelItem(2).child(5).setText(0, _translate("MainWindow", "Linear Array"))
        self.toolsTree.topLevelItem(2).child(6).setText(0, _translate("MainWindow", "Planar Array"))
        self.toolsTree.topLevelItem(2).child(7).setText(0, _translate("MainWindow", "Circular Array"))
        self.toolsTree.topLevelItem(3).setText(0, _translate("MainWindow", "Chapter 4 - Radar Range Equation"))
        self.toolsTree.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "Hertzian Dipole"))
        self.toolsTree.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "Power Density"))
        self.toolsTree.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "Power at Radar Monostatic"))
        self.toolsTree.topLevelItem(3).child(3).setText(0, _translate("MainWindow", "Power at Radar Bistatic"))
        self.toolsTree.topLevelItem(3).child(4).setText(0, _translate("MainWindow", "Minimum Detectable Signal"))
        self.toolsTree.topLevelItem(3).child(5).setText(0, _translate("MainWindow", "Maximum Detection Range"))
        self.toolsTree.topLevelItem(3).child(6).setText(0, _translate("MainWindow", "Power Aperture"))
        self.toolsTree.topLevelItem(3).child(7).setText(0, _translate("MainWindow", "Loop Gain"))
        self.toolsTree.topLevelItem(3).child(8).setText(0, _translate("MainWindow", "Output SNR Monostatic"))
        self.toolsTree.topLevelItem(3).child(9).setText(0, _translate("MainWindow", "Output SNR Search"))
        self.toolsTree.topLevelItem(3).child(10).setText(0, _translate("MainWindow", "Output SNR Bistatic"))
        self.toolsTree.topLevelItem(3).child(11).setText(0, _translate("MainWindow", "Ovals of Cassini"))
        self.toolsTree.topLevelItem(4).setText(0, _translate("MainWindow", "Chapter 5 - Radar Receivers"))
        self.toolsTree.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "Sensitivity Time Control"))
        self.toolsTree.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "Noise Figure"))
        self.toolsTree.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "Low Pass Filter"))
        self.toolsTree.topLevelItem(4).child(3).setText(0, _translate("MainWindow", "Envelope Detector"))
        self.toolsTree.topLevelItem(4).child(4).setText(0, _translate("MainWindow", "Coherent Detector"))
        self.toolsTree.topLevelItem(4).child(5).setText(0, _translate("MainWindow", "Analog to Digital"))
        self.toolsTree.topLevelItem(4).child(6).setText(0, _translate("MainWindow", "ADC Resolution"))
        self.toolsTree.topLevelItem(5).setText(0, _translate("MainWindow", "Chapter 6 - Target Detection"))
        self.toolsTree.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "Probability Distributions"))
        self.toolsTree.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "Gaussian Noise Pd"))
        self.toolsTree.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "Rayleigh Noise Pd"))
        self.toolsTree.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "Single Pulse SNR"))
        self.toolsTree.topLevelItem(5).child(4).setText(0, _translate("MainWindow", "Binary Integration"))
        self.toolsTree.topLevelItem(5).child(5).setText(0, _translate("MainWindow", "Optimum Binary Integration"))
        self.toolsTree.topLevelItem(5).child(6).setText(0, _translate("MainWindow", "Coherent Integration"))
        self.toolsTree.topLevelItem(5).child(7).setText(0, _translate("MainWindow", "Non-Coherent Integration"))
        self.toolsTree.topLevelItem(5).child(8).setText(0, _translate("MainWindow", "Shnidman Approximation"))
        self.toolsTree.topLevelItem(5).child(9).setText(0, _translate("MainWindow", "Constant False Alarm Rate"))
        self.toolsTree.topLevelItem(6).setText(0, _translate("MainWindow", "Chapter 7 - Radar Cross Section"))
        self.toolsTree.topLevelItem(6).child(0).setText(0, _translate("MainWindow", "Infinite Strip"))
        self.toolsTree.topLevelItem(6).child(1).setText(0, _translate("MainWindow", "Infinite Cylinder"))
        self.toolsTree.topLevelItem(6).child(2).setText(0, _translate("MainWindow", "Infinite Cylinder Oblique"))
        self.toolsTree.topLevelItem(6).child(3).setText(0, _translate("MainWindow", "Rectangular Plate"))
        self.toolsTree.topLevelItem(6).child(4).setText(0, _translate("MainWindow", "Stratified Sphere"))
        self.toolsTree.topLevelItem(6).child(5).setText(0, _translate("MainWindow", "Right Circular Cone"))
        self.toolsTree.topLevelItem(6).child(6).setText(0, _translate("MainWindow", "Rounded Nose Cone"))
        self.toolsTree.topLevelItem(6).child(7).setText(0, _translate("MainWindow", "Frustum"))
        self.toolsTree.topLevelItem(6).child(8).setText(0, _translate("MainWindow", "Physical Optics"))
        self.toolsTree.topLevelItem(6).child(9).setText(0, _translate("MainWindow", "Finite Difference Time Domain"))
        self.toolsTree.topLevelItem(7).setText(0, _translate("MainWindow", "Chapter 8 - Pulse Compression"))
        self.toolsTree.topLevelItem(7).child(0).setText(0, _translate("MainWindow", "Stepped Frequency"))
        self.toolsTree.topLevelItem(7).child(1).setText(0, _translate("MainWindow", "Matched Filter"))
        self.toolsTree.topLevelItem(7).child(2).setText(0, _translate("MainWindow", "Stretch Processor"))
        self.toolsTree.topLevelItem(7).child(3).setText(0, _translate("MainWindow", "Single Pulse"))
        self.toolsTree.topLevelItem(7).child(4).setText(0, _translate("MainWindow", "Pulse Train"))
        self.toolsTree.topLevelItem(7).child(5).setText(0, _translate("MainWindow", "LFM Pulse"))
        self.toolsTree.topLevelItem(7).child(6).setText(0, _translate("MainWindow", "LFM Train"))
        self.toolsTree.topLevelItem(7).child(7).setText(0, _translate("MainWindow", "Barker Codes"))
        self.toolsTree.topLevelItem(7).child(8).setText(0, _translate("MainWindow", "Frank Codes"))
        self.toolsTree.topLevelItem(7).child(9).setText(0, _translate("MainWindow", "PRN Codes"))
        self.toolsTree.topLevelItem(8).setText(0, _translate("MainWindow", "Chapter 9 - Target Tracking"))
        self.toolsTree.topLevelItem(8).child(0).setText(0, _translate("MainWindow", "Alpha Beta"))
        self.toolsTree.topLevelItem(8).child(1).setText(0, _translate("MainWindow", "Alpha Beta Gamma"))
        self.toolsTree.topLevelItem(8).child(2).setText(0, _translate("MainWindow", "Kalman Constant Velocity"))
        self.toolsTree.topLevelItem(8).child(3).setText(0, _translate("MainWindow", "Kalman Constant Acceleration"))
        self.toolsTree.topLevelItem(8).child(4).setText(0, _translate("MainWindow", "Kalman Adaptive (epsilon)"))
        self.toolsTree.topLevelItem(8).child(5).setText(0, _translate("MainWindow", "Kalman Adaptive (sigma)"))
        self.toolsTree.topLevelItem(9).setText(0, _translate("MainWindow", "Chapter 10 - Synthetic Aperture Radar"))
        self.toolsTree.topLevelItem(9).child(0).setText(0, _translate("MainWindow", "Back Projection 2D Points"))
        self.toolsTree.topLevelItem(9).child(1).setText(0, _translate("MainWindow", "Back Projection 2D Vehicles"))
        self.toolsTree.topLevelItem(9).child(2).setText(0, _translate("MainWindow", "Back Projection 3D Points"))
        self.toolsTree.topLevelItem(9).child(3).setText(0, _translate("MainWindow", "Back Projection 3D Backhoe"))
        self.toolsTree.topLevelItem(10).setText(0, _translate("MainWindow", "Chapter 11 - Countermeasures"))
        self.toolsTree.topLevelItem(10).child(0).setText(0, _translate("MainWindow", "Jammer to Signal"))
        self.toolsTree.topLevelItem(10).child(1).setText(0, _translate("MainWindow", "Crossover Range"))
        self.toolsTree.topLevelItem(10).child(2).setText(0, _translate("MainWindow", "Burn Through Range"))
        self.toolsTree.topLevelItem(10).child(3).setText(0, _translate("MainWindow", "Delay Line"))
        self.toolsTree.setSortingEnabled(__sortingEnabled)

import Libs.resources_rc
